# Spring Cloud Config本地存储配置
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared # 指定配置文件的位置
  profiles:
    active: native  # 默认从应用的src/main/resource目录下检索配置文件
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD} # 环境变量中配置服务的密码

server:
  port: 8888
